ACADEMIC_CALENDAR_CACHE_NAME = "academic_calendar"
ACADEMIC_CALENDAR_CACHE_FOLDER = "academic_calendar"

MENU_CALENDAR_CACHE_NAME = "menu_calendar"
MENU_PRICE_CACHE_NAME = "menu_price"
REFECTORY_CACHE_FOLDER = "refectory"